### ISSUE TITLE
Black Border with the Image?

### ISSUE THREAD

**Issue by shaadart** [Imgkl/davinci#15] opened 2021-05-23 15:35 UTC
The Plugin is very beautiful it removed my major issues and there is always big praise to its creators,
I always Believe in this kind of Humanful - Opensource. My Experience with this Opensource is very beautiful.
And I am also dedicated to helping grow this Plugin, Amen.

**My Issue**
When I am Capturing Something, it is giving a black border as outputs, 
How can I fix these?

![i love opensource](https://user-images.githubusercontent.com/64954854/119266846-0be23100-bc0a-11eb-8115-73b786922a6a.jpg)

**Comment by Imgkl** [comment] 2021-05-23 15:48
Hi @madd-project,
Thanks for your kind words.  Really appreciate it.😊✌🏽

Can you please provide the code of this component? I'll see what's the issue. I think this happens because of the padding of this component. if you have padding, wrap the padding around the `Davinci` widget. Not as a child of the `Davinci` widget.

**Comment by shaadart** [comment] 2021-05-23 15:58
```
class TodoCard extends StatefulWidget {
  const TodoCard({
    Key key,
  }) : super(key: key);

  @override
  _TodoCardState createState() => _TodoCardState();
}

class _TodoCardState extends State<TodoCard> {
  GlobalKey imageKey;

  //

  @override
  void initState() {
    super.initState();
  }

  //bool isCompleted = false;

  @override
  Widget build(BuildContext context) {
    return Davinci(builder: (key) {
      ///3. set the widget key to the globalkey
      this.imageKey = key;
      return Card(
        // color: Colors.white,
        elevation: 0.7,
        child: Wrap(
          children: [
            ListTile(
              onLongPress: () {},
              leading: IconButton(
                onPressed: () {},

                //   child: ListTile(
                //       trailing: Text("${completedTodo.todoEmoji}"),
                //       title: Text("${completedTodo.todoName}"),
                //       subtitle: Text("${completedTodo.todoRemainder}")),
                // ););

                icon: Icon(CarbonIcons.checkmark_filled, color: Colors.blue),
              ),

              title: Text(
                '${todo.todoName}',
                style: TextStyle(
                  fontFamily: "WorkSans",
                  fontStyle: FontStyle.normal,
                  fontSize: 20,
                  fontWeight: FontWeight.w600,

                  // color: Colors.black54
                ),
              ),

              // subtitle: Text("written on morning"),
            ),

            // Divider(thickness: 1.2),
            ButtonBar(
              children: [
                IconButton(
                  color: Colors.blue,
                  onPressed: () {
                    player.play(
                      'sounds/ui_tap-variant-01.wav',
                      stayAwake: false,
                      // mode: PlayerMode.LOW_LATENCY,
                    );
                    showModalBottomSheet(
                      context: context,
                      isScrollControlled: false,
                      shape: RoundedRectangleBorder(
                        // <-- for border radius
                        borderRadius: BorderRadius.only(
                          topLeft: Radius.circular(10.0),
                          topRight: Radius.circular(10.0),
                        ),
                      ),
                      builder: (context) {
                        return Wrap(
                          children: [
                            FlatButton(
                              onPressed: () async {
                                String fileName =
                                    "${todo.todoName} ${DateTime.now().microsecondsSinceEpoch}";

                                await DavinciCapture.click(
                                  imageKey,
                                  saveToDevice: true,
                                  fileName: fileName,
                                  openFilePreview: true,
                                  albumName: "Toodolees ",
                                );

                                ScaffoldMessenger.of(context)
                                    .showSnackBar(SnackBar(
                                        backgroundColor: Colors.blue[200],
                                        content: Row(
                                          children: [
                                            Expanded(
                                                flex: 1,
                                                child: Text("👍",
                                                    style: TextStyle(
                                                        color: Colors.white))),
                                            Expanded(
                                                flex: 5,
                                                child: Text(
                                                  "Share this Will, (Captured)",
                                                )),
                                          ],
                                        )));
                              },
                              // await DavinciCapture.offStage(
                              //     PreviewWidget());

                              child: ListTile(
                                leading: Icon(CarbonIcons.download),
                                title: Text("Download"),
                              ),
                            ),
                            Divider(),
                          ],
                        );
                      },
                    );
                  },
                  icon: Icon(CarbonIcons.overflow_menu_horizontal),
                ),
              ],
            ),
          ],
        ),
      );
    });
  }
}
```

The Code is of 782 Lines, I made a Trim, If it is not underStandable, i can Package the 782 Lines 😅 ...

**Comment by Imgkl** [comment] 2021-05-23 16:36
Hi @madd-project,

I've identified the cause of black border, it's actually the spacing around the widget (padding and margin)

The culprit is the `Card` widget. The Card widget has margin by default. Making the margin to zero removes the space on the edges and the generated image doesn't have any space for the border.

````
Card(
     margin: EdgeInsets.all(0),   // making the margin as zero.
     color: Colors.amber,
     elevation: 0.7,
     child: Wrap(.......),
),
````

 If this is not the desired behaviour you could implement your own widget using Container that looks like a Card.

I've tested this and I've confirmed that's the issue. So I'm gonna go ahead and close this issue. Feel free to reopen this issue if you face any issues or any help. 😊 Happy coding.

**Closed as completed by Imgkl** 2021-05-23 16:36 UTC
Labels: testing needed, possible bug

**Comment by shaadart** [comment] 2021-05-23 17:02
![Screenshot_20210523-222939.jpg](https://user-images.githubusercontent.com/64954854/119269686-8e70ed80-bc16-11eb-9c58-4044f5379a5c.jpg)
Now, the UI cards has joined themselves.

**Comment by Imgkl** [comment] 2021-05-23 17:08
Can you try this...

````
 Padding(
        padding: const EdgeInsets.all(8.0), // add padding as a parent component to the davinci widget.
        child: Davinci(builder: (key) {
          ///3. set the widget key to the globalkey
          this.imageKey = key;
          return Card(
            margin: EdgeInsets.all(0),
            color: Colors.amber,
            elevation: 0.7,
            child: Wrap(....),
              ),
      },
  ),
);
````

**Comment by shaadart** [comment] 2021-05-24 03:53
I guess we are just one Small Problem away, 
The Last Problem is this, There is Still, Jet-Blacky Thing at the ```corners``` the Sides are Resolved but the Corners are Trouble Makers, ..

**Comment by shaadart** [comment] 2021-05-24 04:00
![can you see the black borders at the corners](https://user-images.githubusercontent.com/64954854/119294661-99f20200-bc72-11eb-9401-a1fdcfc8d9d7.jpg)

**Comment by Imgkl** [comment] 2021-05-24 04:38
Hey @madd-project,

The generated image is in png format. Any padding/margin around the widget can create a transparent layer in the png. It is how png image works. The black border is not actually black it is a space around the widget, that created a transparent layer in the image. 

one way to not having any border to your component is, you can go ahead and change the card's border radius. But it may not be visually pleasing.

https://stackoverflow.com/questions/50756745/custom-card-shape-flutter-sdk

**Comment by shaadart** [comment] 2021-05-24 05:39
I found a Good Alternative, One who can Face Troooooble in this, He can surely, use this, 

![can you see the black borders at the corners](https://user-images.githubusercontent.com/64954854/119300028-ad569a80-bc7d-11eb-8bf0-e574f013e079.jpg)

**The Benefit:** If you Use this Widget in Instagram Stories of Status or any other Social place, you will see the border which will help you distinguish, what actually is this thing.

If this Above is Feeling Appealing to You and is better to use this Transparent -like a color other than Black then, (Thanks Lord, Davinci, and @Imgkl for the Opportunity to share some knowledge).
So, 

```
            return Davinci(builder: (key) {
                        ///3. set the widget key to the globalkey
                        this.imageKey = key;
                        return Container(
                          color: Colors.transparent,
                          child: Card(
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(0),
                            ),
                            margin: EdgeInsets.all(0),
                           

                             color: Theme.of(context).canvasColor
                            ]),
                            child: Card(
                              child: Wrap(....)
```

I am in Love with this Package, You made the most powerful and perennial selling Package, and the most powerful is that this is open to each individual in this world. Love you, and thanks for all quick Responses my Most Beloved Friend.
